apiVersion: v1
kind: Secret
metadata:
  name: digitify-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://github.com/Muhammad-Imtiaz/digitify-devops-assessment.git
  password: ghp_reIjddtRWgjEenN9QpOXburlp8Sv5deN4CAy5V
  username: Muhammad-Imtiaz
